global:
  scrape_interval: 15s # Recolher métricas a cada 15 segundos

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # O próprio Prometheus

  - job_name: 'strategy-framework'
    static_configs:
      - targets: ['host.docker.internal:9092'] # O nosso serviço Python (exposto em 9092)

  - job_name: 'risk-engine'
    static_configs:
      - targets: ['host.docker.internal:9093'] # O nosso serviço Rust (exposto em 9093)

  - job_name: 'coinbase-connector'
    static_configs:
      - targets: ['host.docker.internal:9091'] # O nosso serviço Rust (exposto em 9091)
      
  # NOTA: 'host.docker.internal' é um nome DNS especial dentro do Docker
  # que permite ao container (Prometheus) aceder a serviços a correr na máquina host.