# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trading_system.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trading_system.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14trading_system.proto\x12\x0etrading_system\"@\n\rTradingSignal\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x01\x12\r\n\x05price\x18\x03 \x01(\x01\"?\n\x0cOrderRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x01\x12\r\n\x05price\x18\x03 \x01(\x01\"1\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2[\n\nRiskEngine\x12M\n\rProcessSignal\x12\x1d.trading_system.TradingSignal\x1a\x1d.trading_system.OrderResponse2e\n\x10\x45xecutionService\x12Q\n\x12PlaceLimitBuyOrder\x12\x1c.trading_system.OrderRequest\x1a\x1d.trading_system.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trading_system_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRADINGSIGNAL']._serialized_start=40
  _globals['_TRADINGSIGNAL']._serialized_end=104
  _globals['_ORDERREQUEST']._serialized_start=106
  _globals['_ORDERREQUEST']._serialized_end=169
  _globals['_ORDERRESPONSE']._serialized_start=171
  _globals['_ORDERRESPONSE']._serialized_end=220
  _globals['_RISKENGINE']._serialized_start=222
  _globals['_RISKENGINE']._serialized_end=313
  _globals['_EXECUTIONSERVICE']._serialized_start=315
  _globals['_EXECUTIONSERVICE']._serialized_end=416
# @@protoc_insertion_point(module_scope)
